<? # ?>


<!-- Header hero -->
<div id="header-hero-device" class="tinted">
<div id="header-hero-device" class="hero-block text-light height-small tinted">
<img class="background tinted" src="images/pheme-welcome-banner.jpg">
<h1><?= $page_title ?></h1>
<p></p>
</div>
</div>


<div class="column-three-quarter">


<!-- Three main links from this page;
        icon-link-blocks needs to allow copy! -->
<ul class="icon-link-blocks">
<li>
<a href="#"><img src="images/icon-students.jpg" alt="" />Students</a>
<!--<p>You are an enrolled student. The eight-digit student number on your Campus Card starts with a 1 or 2.</p>-->
</li>
<li>
<a href="#"><img src="images/icon-staff.jpg" alt="" />Staff</a>
<!--<p>You are a staff member or closely associated with the University. The eight-digit staff number on your Campus Card starts  with a zero.</p>-->
</li>
<li>
<a href="#"><img src="images/icon-visitors.jpg" alt="" />Visitors</a>
<!--<p>You are temporarily associated with the University. The five digits of your Person ID on your Campus Card will have 5, A, B, F, L, M, R or V as a prefix.</p>-->
</li>
</ul>


</div><!-- .column-quarter -->
<div class="column-quarter">


<!-- "Further information" sidebar -->
<div class="form-device">
<h3>Need help?</h3>
<div>
<p class="text-blue"><b>Students</b></p>
<ul class="links">
<li><a href="#">Information for students</a></li>
<li><a href="#">Information services</a></li>
</ul>
<p class="text-blue"><b>Staff, visitors and others</b></p>
<ul class="links">
<li><a href="#">Information for staff</a></li>
<li><a href="#">Information for visitors &amp; others</a></li>
</ul>
</div>
</div>


</div><!-- .column-quarter -->


<? include('content-contact-us.html'); ?>
