<? # ?>



<div class="form-errors">%form_errors%</div>


<div class="column-three-quarter">


<div class="form-device width-full">
<form action="">
<h3>Sign on</h3>
<dl>
<dt>Staff, student or visitor ID:</dt>
<dd><input type="text" name="TODO" required />
<dt>Pheme password:</dt>
<dd><input type="text" name="TODO" required />
</dl>
</div>


<div>
<h3>Ending your session</h3>
<p>You will remain logged into the SSO network until you close all web browser windows. To protect your privacy ensure you close all browser windows when you are finished. If you are using a public computer you should log out.</p>
<p>Your SSO session will also end after 30 minutes of inactivity.</p>
</div>


</div><!-- .column-quarter -->
<div class="column-quarter">


<!-- "Further information" sidebar -->
<div class="form-device">
<h3>Need to activate your account?</h3>
<p>If you are logging on for the first time you will need to activate your
Pheme account. Please select one of the following accounts to activate.</p>
<p><a class="button outline" href="TODO">Students</a></p>
<p><a class="button outline" href="TODO">Staff</a></p>
<p class="margin-bottom"><a class="button outline" href="TODO">Visitors</a></p>



</div><!-- .column-quarter -->


<? include('content-contact-us.html'); ?>
