

<!-- Header hero -->
<div id="header-hero-device" class="tinted">
  <div id="header-hero-device" class="hero-block text-light height-small tinted">
    <img class="background tinted" src="//static.weboffice.uwa.edu.au/visualid/sites/uwa_accept/images/pheme-welcome-banner.jpg">
    <h1><?= $inner_page_title ?></h1>
    <p>Pheme is the UWA Access Management System, a place where you can set a
       password for your central university account giving you access to a
       range of services.</p>
  </div>
</div>


<div class="column-three-quarter">


<!-- Three main links from this page;
        icon-link-blocks needs to allow copy! -->
<ul class="icon-link-blocks">
  <li>
    <a href="TODO">
      <img src="//static.weboffice.uwa.edu.au/visualid/sites/uwa_accept/images/icon-students.jpg" alt="" />
      <h4>Students</h4>
      <p>You are an enrolled student. The eight-digit student number on your
         Campus Card starts with a 1 or 2.</p>
    </a>
  </li>
  <li>
    <a href="TODO">
      <img src="//static.weboffice.uwa.edu.au/visualid/sites/uwa_accept/images/icon-staff.jpg" alt="" />
      <h4>Staff</h4>
      <p>You are a staff member or closely associated with the University. The
         eight-digit staff number on your Campus Card starts  with a zero.</p>
    </a>
  </li>
  <li>
    <a href="TODO">
      <img src="//static.weboffice.uwa.edu.au/visualid/sites/uwa_accept/images/icon-visitors.jpg" alt="" />
      <h4>Visitors</h4>
      <p>You are temporarily associated with the University. The five digits of
         your Person ID on your Campus Card will have 5, A, B, F, L, M, R or V
         as a prefix.</p></a>
  </li>
</ul>


</div><!-- .column-quarter -->
<div class="column-quarter">


<!-- "Further information" sidebar -->
<div class="form-device">
  <h3>Need help?</h3>
  <div>
    <p class="text-blue"><b>Students</b></p>
    <ul class="links">
      <li><a href="#">Information for students</a></li>
      <li><a href="#">Information services</a></li>
    </ul>
    <p class="text-blue"><b>Staff, visitors and others</b></p>
    <ul class="links">
      <li><a href="#">Information for staff</a></li>
      <li><a href="#">Information for visitors &amp; others</a></li>
    </ul>
  </div>
</div>


</div><!-- .column-quarter -->


<? include('content-contact-us.html'); ?>
