<? /*

    # okay these all seem to be included via the default template (grabbed from Matrix) already...

<script type="text/javascript" src="//static.weboffice.uwa.edu.au/visualid/lib/jquery/jquery-1.11.latest.js"></script>  
<!-- NB: The number after 'refresh=15_' is just a day-of-the-year cache-buster -->
<script id="uwacore-rebrand-script" type="text/javascript" src="//static.weboffice.uwa.edu.au/visualid/core-rebrand/js/uwacore.js?refresh=15_<?= date('z'); ?>"></script>
<link id="uwacore-rebrand-style" rel="stylesheet" type="text/css" href="//static.weboffice.uwa.edu.au/visualid/core-rebrand/css/uwacore.css?refresh=15_<?= date('z'); ?>" />
<link rel="stylesheet" type="text/css" href="http://static.weboffice.uwa.edu.au/visualid/lib/font-awesome/font-awesome.4.latest.css?r4" />
<link rel="stylesheet" type="text/css" href="//static.weboffice.uwa.edu.au/visualid/core-rebrand/css/megamenu.css?r5" />
<script async type="text/javascript" src="//static.weboffice.uwa.edu.au/visualid/core-rebrand/js/megamenu.js?r5"></script>
*/ ?>
