<script type="text/javascript" src="//static.weboffice.uwa.edu.au/visualid/lib/jquery/jquery-1.11.latest.js"></script>  
<script id="uwacore-rebrand-script" type="text/javascript" src="//static.weboffice.uwa.edu.au/visualid/core-rebrand/js/uwacore.js?refresh=15_%globals_date_z%"></script>
<link id="uwacore-rebrand-style" rel="stylesheet" type="text/css" href="//static.weboffice.uwa.edu.au/visualid/core-rebrand/css/uwacore.css?refresh=15_%globals_date_z%" />
<link rel="stylesheet" type="text/css" href="http://static.weboffice.uwa.edu.au/visualid/lib/font-awesome/font-awesome.4.latest.css?r4" />
<link rel="stylesheet" type="text/css" href="//static.weboffice.uwa.edu.au/visualid/core-rebrand/css/megamenu.css?r5" />
<script async type="text/javascript" src="//static.weboffice.uwa.edu.au/visualid/core-rebrand/js/megamenu.js?r5"></script>

<meta name="google-site-verification" content="Lxo0TTbWrLWwWDYgdNJ6_Hi8w1LB0T2r20erqMtwLYI" />

